### ISSUE TITLE
Failed to start 

### ISSUE THREAD

**Issue by Wannab007** [acl1704/pterodactyl-empyrion#1]
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 10.5
Current timezone: Etc/UTC
wine-5.0.2
steam user is not set.

Using anonymous user.

No appid set. Starting Server
First launch will throw some errors. Ignore them
:/home/container$ wine ./DedicatedServer/EmpyrionDedicated.exe -batchmode -log -logFile Logs/current.log "$@" &> Logs/wine.log | tail -f Logs/current.log
/entrypoint.sh: line 84: Logs/wine.log: No such file or directory
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
tail: cannot open 'Logs/current.log' for reading: No such file or directory
tail: no files remaining
container@pterodactyl~ Server marked as offline...

[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by Wannab007** [comment]
I found this egg from the parkervpc git issues, Empyrion - Galactic Survival #487

**Comment by acl1704** [comment]
Try now, I've fixed the log problem. Still looking for a solution for the lack of realtime console output and 'start' status change.
