### ISSUE TITLE
Latest Egg Causes 500 server error when importing

### ISSUE THREAD

**Issue by Wannab007** [acl1704/pterodactyl-empyrion#3]
I tried to import the new egg after deleting the old one. I get 500 server error when doing so. All other eggs from parkervcp upload without issue so I am going to assume it is an issue with this egg.

**Comment by acl1704** [comment]
Not an egg issue. See bugfix on https://github.com/pterodactyl/panel/commit/b00def253746d1c96ba2c4bdc232d436fd7b7fee
